#!/usr/bin/env node

/**
 * CLIENT SETUP SCRIPT
 * 
 * This script initializes your client template with:
 * - Default color theme from client configuration
 * - Default footer settings from client configuration
 * - Default legal content from client configuration
 * - Default admin user from environment variables
 * 
 * Run this script after:
 * 1. Setting up your .env file
 * 2. Customizing your client.config.js
 * 3. Placing your logo files in the /public folder
 * 
 * Usage: npm run setup-client
 */

require('dotenv').config();
const mongoose = require('mongoose');
const bcrypt = require('bcrypt');
const fs = require('fs');
const path = require('path');

// Import client configuration
const clientConfig = require('../client.config.js');

// MongoDB connection
async function connectDB() {
  try {
    const mongoUri = process.env.MONGODB_URI;
    if (!mongoUri) {
      throw new Error('MONGODB_URI environment variable is required');
    }
    
    await mongoose.connect(mongoUri);
    console.log('✅ Connected to MongoDB');
  } catch (error) {
    console.error('❌ MongoDB connection failed:', error);
    process.exit(1);
  }
}

// User schema and model with rank field
const userSchema = new mongoose.Schema({
  name: { type: String, required: true },
  mail: { type: String, required: true, unique: true },
  password: { type: String, required: true },
  rank: { 
    type: String, 
    enum: ["Developer", "Eigenaar", "Manager", "Werknemer"],
    default: "Werknemer" 
  },
  created_at: { type: Date, default: Date.now },
  updated_at: { type: Date, default: Date.now },
});

const User = mongoose.models.User || mongoose.model('User', userSchema);

// Footer schema and model
const footerColumnSchema = new mongoose.Schema({
  title: { type: String, required: true },
  items: [{
    text: { type: String, required: true },
    link: { type: String, required: false },
    isExternal: { type: Boolean, default: false }
  }]
});

const socialMediaSchema = new mongoose.Schema({
  youtube: { type: String, default: "" },
  facebook: { type: String, default: "" },
  instagram: { type: String, default: "" },
  twitter: { type: String, default: "" },
  linkedin: { type: String, default: "" }
}, { _id: false });

const contactInfoSchema = new mongoose.Schema({
  name: { type: String, default: "" },
  address: { type: String, default: "" },
  phone: { type: String, default: "" },
  email: { type: String, default: "" }
}, { _id: false });

const footerSchema = new mongoose.Schema({
  columns: { type: [footerColumnSchema], required: true },
  socialMedia: { type: socialMediaSchema, required: true },
  contactInfo: { type: contactInfoSchema, required: true },
  backgroundColor: { type: String, default: "#202020" },
  textColor: { type: String, default: "#fefefe" },
  created_at: { type: Date, default: Date.now },
  updated_at: { type: Date, default: Date.now },
});

const Footer = mongoose.models.Footer || mongoose.model('Footer', footerSchema);

// Legal settings schema and model
const legalSchema = new mongoose.Schema({
  disclaimer: { type: String, default: '' },
  privacyPolicy: { type: String, default: '' }
});

const LegalSettings = mongoose.models.LegalSettings || mongoose.model('LegalSettings', legalSchema);

// Setup color theme
async function setupColorTheme() {
  try {
    console.log('🎨 Setting up color theme...');
    
    const colors = clientConfig.theme.colors;
    
    const scssContent = `// Theme colors - Generated by setup script
$primary: ${colors.primary};
$secondary: ${colors.secondary};
$accent: ${colors.accent};
$text: ${colors.text};
$background: ${colors.background};

$dark: #1b1b1b;
$light: #f3f3f3;

:root {
  --primary: #{$primary};
  --secondary: #{$secondary};
  --accent: #{$accent};
  --text: #{$text};
  --background: #{$background};
}`;

    const filePath = path.join(process.cwd(), 'src/styles/variables.scss');
    await fs.promises.writeFile(filePath, scssContent, 'utf-8');
    
    console.log('✅ Color theme updated successfully');
  } catch (error) {
    console.error('❌ Error setting up color theme:', error);
  }
}

// Setup default admin user
async function setupAdminUser() {
  try {
    console.log('👤 Setting up admin user...');
    
    const adminName = process.env.ADMIN_NAME;
    const adminEmail = process.env.ADMIN_EMAIL;
    const adminPassword = process.env.ADMIN_PASSWORD;
    
    if (!adminName || !adminEmail || !adminPassword) {
      console.log('⚠️ Admin user environment variables not set. Skipping admin user creation.');
      console.log('Set ADMIN_NAME, ADMIN_EMAIL, and ADMIN_PASSWORD in your .env file to create an admin user.');
      return;
    }
    
    // Check if admin user already exists
    const existingUser = await User.findOne({ mail: adminEmail });
    if (existingUser) {
      // Update existing user to Developer rank if not already set
      if (!existingUser.rank || existingUser.rank !== "Developer") {
        existingUser.rank = "Developer";
        await existingUser.save();
        console.log('✅ Admin user updated to Developer rank');
        console.log(`📧 Email: ${adminEmail}`);
        console.log('👑 Rank: Developer (full access)');
      } else {
        console.log('ℹ️ Admin user already exists with Developer rank. Skipping creation.');
      }
      return;
    }
    
    // Hash password
    const saltRounds = 10;
    const hashedPassword = await bcrypt.hash(adminPassword, saltRounds);
    
    // Create admin user with Developer rank
    const adminUser = new User({
      name: adminName,
      mail: adminEmail,
      password: hashedPassword,
      rank: "Developer",
    });
    
    await adminUser.save();
    console.log('✅ Admin user created successfully with Developer rank');
    console.log(`📧 Email: ${adminEmail}`);
    console.log('🔐 Password: (from environment variable)');
    console.log('👑 Rank: Developer (full access)');
  } catch (error) {
    console.error('❌ Error setting up admin user:', error);
  }
}

// Setup footer settings
async function setupFooterSettings() {
  try {
    console.log('🦶 Setting up footer settings...');
    
    // Check if footer settings already exist
    const existingFooter = await Footer.findOne();
    if (existingFooter) {
      console.log('ℹ️ Footer settings already exist. Skipping creation.');
      return;
    }
    
    const footerData = {
      columns: clientConfig.footer.columns,
      socialMedia: clientConfig.socialMedia,
      contactInfo: clientConfig.contact,
      backgroundColor: clientConfig.footer.backgroundColor,
      textColor: clientConfig.footer.textColor,
    };
    
    const footer = new Footer(footerData);
    await footer.save();
    
    console.log('✅ Footer settings created successfully');
  } catch (error) {
    console.error('❌ Error setting up footer settings:', error);
  }
}

// Setup legal settings
async function setupLegalSettings() {
  try {
    console.log('⚖️ Setting up legal settings...');
    
    // Check if legal settings already exist
    const existingLegal = await LegalSettings.findOne();
    if (existingLegal) {
      console.log('ℹ️ Legal settings already exist. Skipping creation.');
      return;
    }
    
    const legalData = {
      disclaimer: clientConfig.legal.disclaimer,
      privacyPolicy: clientConfig.legal.privacyPolicy,
    };
    
    const legal = new LegalSettings(legalData);
    await legal.save();
    
    console.log('✅ Legal settings created successfully');
  } catch (error) {
    console.error('❌ Error setting up legal settings:', error);
  }
}

// Main setup function
async function main() {
  console.log('🚀 Starting client template setup...\n');
  
  // Validate environment variables
  if (!process.env.MONGODB_URI) {
    console.error('❌ MONGODB_URI environment variable is required');
    console.log('📝 Please create a .env file based on env.example');
    process.exit(1);
  }
  
  if (!process.env.JWT_SECRET) {
    console.error('❌ JWT_SECRET environment variable is required');
    console.log('📝 Please create a .env file based on env.example');
    process.exit(1);
  }
  
  // Check email configuration (optional but if one is set, all should be set)
  const emailVars = ['EMAIL_HOST', 'EMAIL_PORT', 'EMAIL_USER', 'EMAIL_PASS', 'EMAIL_RECIPIENT'];
  const emailVarsSet = emailVars.filter(varName => process.env[varName]);
  
  if (emailVarsSet.length > 0 && emailVarsSet.length < emailVars.length) {
    console.log('⚠️ Email configuration incomplete:');
    emailVars.forEach(varName => {
      const isSet = process.env[varName] ? '✅' : '❌';
      console.log(`  ${isSet} ${varName}`);
    });
    console.log('📝 Set all email variables in .env file for contact form functionality');
  } else if (emailVarsSet.length === emailVars.length) {
    console.log('📧 Email configuration detected and validated');
  } else {
    console.log('📭 Email configuration not provided (contact form will not work)');
  }
  
  try {
    // Connect to database
    await connectDB();
    
    // Run setup tasks
    await setupColorTheme();
    await setupAdminUser();
    await setupFooterSettings();
    await setupLegalSettings();
    
    console.log('\n🎉 Client template setup completed successfully!');
    console.log('\n📋 Next steps:');
    console.log('1. Replace /public/CollabIndex_main.png with your company logo');
    console.log('2. Replace favicon files in /public with your favicons');
    console.log('3. Run "npm run dev" to start development server');
    console.log('4. Visit /adm/login to access admin panel');
    
  } catch (error) {
    console.error('❌ Setup failed:', error);
    process.exit(1);
  } finally {
    await mongoose.disconnect();
    console.log('👋 Disconnected from MongoDB');
  }
}

// Run the setup
if (require.main === module) {
  main();
}

module.exports = { main }; 