#!/usr/bin/env node

/**
 * CLIENT SETUP SCRIPT
 * 
 * This script initializes your client template with:
 * - Default color theme from client configuration
 * - Default footer settings from client configuration
 * - Default legal content from client configuration
 * - Default admin user from environment variables
 * 
 * Run this script after:
 * 1. Setting up your .env file
 * 2. Customizing your client.config.js
 * 3. Placing your logo files in the /public folder
 * 
 * Usage: npm run setup-client
 */

require('dotenv').config();
const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcrypt');
const fs = require('fs');
const path = require('path');

// Import client configuration
const clientConfig = require('../client.config.js');

// Initialize Prisma Client
const prisma = new PrismaClient();

// Setup color theme
async function setupColorTheme() {
  try {
    console.log('🎨 Setting up color theme...');
    
    const colors = clientConfig.theme.colors;
    
    const scssContent = `// Theme colors - Generated by setup script
$primary: ${colors.primary};
$secondary: ${colors.secondary};
$accent: ${colors.accent};
$text: ${colors.text};
$background: ${colors.background};

$dark: #1b1b1b;
$light: #f3f3f3;

:root {
  --primary: #{$primary};
  --secondary: #{$secondary};
  --accent: #{$accent};
  --text: #{$text};
  --background: #{$background};
}`;

    const filePath = path.join(process.cwd(), 'src/styles/variables.scss');
    await fs.promises.writeFile(filePath, scssContent, 'utf-8');
    
    console.log('✅ Color theme updated successfully');
  } catch (error) {
    console.error('❌ Error setting up color theme:', error);
  }
}

// Setup default admin user
async function setupAdminUser() {
  try {
    console.log('👤 Setting up admin user...');
    
    const adminName = process.env.ADMIN_NAME;
    const adminEmail = process.env.ADMIN_EMAIL;
    const adminPassword = process.env.ADMIN_PASSWORD;
    
    if (!adminName || !adminEmail || !adminPassword) {
      console.log('⚠️ Admin user environment variables not set. Skipping admin user creation.');
      console.log('Set ADMIN_NAME, ADMIN_EMAIL, and ADMIN_PASSWORD in your .env file to create an admin user.');
      return;
    }
    
    // Check if admin user already exists
    const existingUser = await prisma.user.findUnique({
      where: { mail: adminEmail }
    });
    
    if (existingUser) {
      // Update existing user to Developer rank if not already set
      if (!existingUser.rank || existingUser.rank !== "Developer") {
        await prisma.user.update({
          where: { id: existingUser.id },
          data: { rank: "Developer" }
        });
        console.log('✅ Admin user updated to Developer rank');
        console.log(`📧 Email: ${adminEmail}`);
        console.log('👑 Rank: Developer (full access)');
      } else {
        console.log('ℹ️ Admin user already exists with Developer rank. Skipping creation.');
      }
      return;
    }
    
    // Hash password
    const saltRounds = 10;
    const hashedPassword = await bcrypt.hash(adminPassword, saltRounds);
    
    // Create admin user with Developer rank
    await prisma.user.create({
      data: {
        name: adminName,
        mail: adminEmail,
        password: hashedPassword,
        rank: "Developer",
      }
    });
    
    console.log('✅ Admin user created successfully with Developer rank');
    console.log(`📧 Email: ${adminEmail}`);
    console.log('🔐 Password: (from environment variable)');
    console.log('👑 Rank: Developer (full access)');
  } catch (error) {
    console.error('❌ Error setting up admin user:', error);
  }
}

// Setup footer settings
async function setupFooterSettings() {
  try {
    console.log('🦶 Setting up footer settings...');
    
    // Check if footer settings already exist
    const existingFooter = await prisma.footer.findFirst();
    if (existingFooter) {
      console.log('ℹ️ Footer settings already exist. Skipping creation.');
      return;
    }
    
    const footerData = {
      columns: clientConfig.footer.columns,
      socialMedia: clientConfig.socialMedia,
      contactInfo: clientConfig.contact,
      backgroundColor: clientConfig.footer.backgroundColor,
      textColor: clientConfig.footer.textColor,
    };
    
    await prisma.footer.create({
      data: footerData
    });
    
    console.log('✅ Footer settings created successfully');
  } catch (error) {
    console.error('❌ Error setting up footer settings:', error);
  }
}

// Setup legal settings
async function setupLegalSettings() {
  try {
    console.log('⚖️ Setting up legal settings...');
    
    // Check if legal settings already exist
    const existingLegal = await prisma.legalSettings.findFirst();
    if (existingLegal) {
      console.log('ℹ️ Legal settings already exist. Skipping creation.');
      return;
    }
    
    const legalData = {
      disclaimer: clientConfig.legal.disclaimer,
      privacyPolicy: clientConfig.legal.privacyPolicy,
    };
    
    await prisma.legalSettings.create({
      data: legalData
    });
    
    console.log('✅ Legal settings created successfully');
  } catch (error) {
    console.error('❌ Error setting up legal settings:', error);
  }
}

// Main setup function
async function main() {
  console.log('🚀 Starting client template setup...\n');
  
  // Validate environment variables
  if (!process.env.DATABASE_URL) {
    console.error('❌ DATABASE_URL environment variable is required');
    console.log('📝 Please create a .env file with DATABASE_URL pointing to your PostgreSQL database');
    process.exit(1);
  }
  
  if (!process.env.JWT_SECRET) {
    console.error('❌ JWT_SECRET environment variable is required');
    console.log('📝 Please create a .env file based on env.example');
    process.exit(1);
  }
  
  // Check email configuration (optional but if one is set, all should be set)
  const emailVars = ['EMAIL_HOST', 'EMAIL_PORT', 'EMAIL_USER', 'EMAIL_PASS', 'EMAIL_RECIPIENT'];
  const emailVarsSet = emailVars.filter(varName => process.env[varName]);
  
  if (emailVarsSet.length > 0 && emailVarsSet.length < emailVars.length) {
    console.log('⚠️ Email configuration incomplete:');
    emailVars.forEach(varName => {
      const isSet = process.env[varName] ? '✅' : '❌';
      console.log(`  ${isSet} ${varName}`);
    });
    console.log('📝 Set all email variables in .env file for contact form functionality');
  } else if (emailVarsSet.length === emailVars.length) {
    console.log('📧 Email configuration detected and validated');
  } else {
    console.log('📭 Email configuration not provided (contact form will not work)');
  }
  
  try {
    // Test database connection
    await prisma.$connect();
    console.log('✅ Connected to database');
    
    // Run setup tasks
    await setupColorTheme();
    await setupAdminUser();
    await setupFooterSettings();
    await setupLegalSettings();
    
    console.log('\n🎉 Client template setup completed successfully!');
    console.log('\n📋 Next steps:');
    console.log('1. Replace /public/CollabIndex_main.png with your company logo');
    console.log('2. Replace favicon files in /public with your favicons');
    console.log('3. Run "npm run dev" to start development server');
    console.log('4. Visit /adm/login to access admin panel');
    
  } catch (error) {
    console.error('❌ Setup failed:', error);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
    console.log('👋 Disconnected from database');
  }
}

// Run the setup
if (require.main === module) {
  main();
}

module.exports = { main };
